### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by Andr1yK**

### CODE REVIEW

**Review by alexandra-protyanova — CHANGES_REQUESTED** [review]
Bad job!

**Review by Bohdan-Maksymiuk — APPROVED** [review]
Great!

**Review by ArturErmolenko — CHANGES_REQUESTED** [review]
please look at checklist, your code look like shit

**Comment by Bohdan-Maksymiuk** [comment]
> please look at checklist, your code look like shit

@ArturErmolenko you are not right. Great code. In production!

**Review by ArturErmolenko — APPROVED** [review]
@Bohdan-Maksymiuk I have no right to argue with you) so let it be 🔥

**Review by OleksiiBlezniuk — CHANGES_REQUESTED** [review]
please install linter
follow indentation rules and semantic

**Pull request closed without merging**
