### PR TITLE
Button not changing

### PR DESCRIPTION
**Pull request by OlyaProkofieva**

### CODE REVIEW

**Comment by KseniaSkr** [comment]
[DEMO LINK](https://KseniaSkr.github.io/layout_hello-world/)
[TEST REPORT LINK](https://KseniaSkr.github.io/layout_hello-world/report/html_report/)

**Comment by andrii-rykal** [comment]
[DEMO LINK](https://andrii-rykal.github.io/layout_hello-world/)
 [TEST REPORT LINK](https://andrii-rykal.github.io/layout_hello-world/report/html_report/)

**Comment by BondarenkoDmitriy** [comment]
[DEMO LINK](https://BondarenkoDmitriy.github.io/layout_hello-world/)
[TEST REPORT LINK](https://BondarenkoDmitriy.github.io/layout_hello-world/report/html_report/)

**Comment by Sadeni-09** [comment]
- [DEMO LINK](https://Sadeni-09.github.io/layout_hello-world/)
- [TEST REPORT LINK](https://Sadeni-09.github.io/layout_hello-world/report/html_report/)

**Comment by Walintigo** [comment]
new pul

**Pull request closed without merging**
