### PR TITLE
add solution

### PR DESCRIPTION
**Pull request by ViktorTsupa**
- [DEMO LINK](https://ViktorTsupa.github.io/layout_hello-world/)
- [TEST REPORT LINK](https://ViktorTsupa.github.io/layout_hello-world/report/html_report/)

### CODE REVIEW

**Comment by maristella12** [comment]
- [DEMO LINK](https://maristella12.github.io/layout_hello-world/)
- [TEST REPORT LINK](https://maristella12.github.io/layout_hello-world/report/html_report/)

**Comment by gazebo88fire** [comment]
- [DEMO LINK](https://gazebo88fire.github.io/layout_hello-world/)
- [TEST REPORT LINK](https://gazebo88fire.github.io/layout_hello-world/report/html_report/)

**Comment by Antonio777148** [comment]
- [DEMO LINK](https://<Antonio777148>.github.io/layout_hello-world/)
- [TEST REPORT LINK](https://<Antonio777148>.github.io/layout_hello-world/report/html_report/)

**Comment by dokrod** [comment]
- [DEMO LINK](https://dokrod.github.io/layout_hello-world/)
- [TEST REPORT LINK](https://dokrod.github.io/layout_hello-world/report/html_report/)

**Comment by Oleksandr-Piechieniev** [comment]
- [DEMO LINK](https://Oleksandr-Piechieniev.github.io/layout_moyo-header/)
- [TEST REPORT LINK](https://Oleksandr-Piechieniev.github.io/layout_moyo-header/report/html_report/)

**Pull request closed without merging**
