### PR TITLE
add task solution

### PR DESCRIPTION
**Pull request by MaksymTarasov**
- [DEMO LINK](https://MaksymTarasov.github.io/layout_hello-world/)
- [TEST REPORT LINK](https://MaksymTarasov.github.io/layout_hello-world/report/html_report/)

### CODE REVIEW

**Review by polosanya — CHANGES_REQUESTED** [review]
Demo link doesn't work(
Please make sure that you deployed the page correctly
image

**Comment by MaksymTarasov** [comment]
> Demo link doesn't work( Please make sure that you deployed the page correctly image



> Demo link doesn't work( Please make sure that you deployed the page correctly image

hello, try once more.

**Review by And678 — APPROVED** [review]
Works correctly now :+1:

**Review by And678 — APPROVED** [review]
ignore this, second approve for the system

**Pull request closed without merging**
